openapi: 3.1.0
info:
  title: Project Structuring Framework API
  description: A RESTful API for managing hierarchical work packages and linking Gherkin requirements to goals, as defined in the KAOS model.
  version: 1.0.0
servers:
  - url:  https://lyhs3000.loca.lt/
    description: Local development server
paths:
  /work-packages:
    get:
      operationId: listWorkPackages
      summary: List all work packages
      description: Retrieve a list of all work packages, optionally filtered by parent package.
      responses:
        '200':
          description: List of work packages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    parentPackagePath:
                      type: string
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
